shimmy_image_config_version=1
image_source=external
image_upstream_ref=ghcr.io/fluxcd/flux-cli:v2.9.4
image_default_ref=ghcr.io/fluxcd/flux-cli@sha256:5260c79fb1b744c78755d98bcb271971c93e4ea214623c3f9f96ff59536d0398
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
