shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-oc-4_22
image_base_count=1
image_base_1_build_arg=SHIMMY_OC_4_22_BASE_IMAGE
image_base_1_upstream_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:83541f26b665963dea277a7f893725f4a1812b0550d07404f1429ed8da6b3bb2
image_base_1_default_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:83541f26b665963dea277a7f893725f4a1812b0550d07404f1429ed8da6b3bb2
image_base_1_registry_access=authenticated
image_platform=linux/amd64
image_platform=linux/arm64
