shimmy_image_config_version=1
image_source=external
image_upstream_ref=ghcr.io/jqlang/jq:1.8.1
image_default_ref=ghcr.io/jqlang/jq@sha256:4f34c6d23f4b1372ac789752cc955dc67c2ae177eb1b5860b75cdc5091ce6f91
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
