shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-oc-4_20
image_base_count=1
image_base_1_build_arg=SHIMMY_OC_4_20_BASE_IMAGE
image_base_1_upstream_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:61136a31003a378aae4039be61cfe10f3d2b60399f08a5325233826deb569383
image_base_1_default_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:61136a31003a378aae4039be61cfe10f3d2b60399f08a5325233826deb569383
image_base_1_registry_access=authenticated
image_platform=linux/amd64
image_platform=linux/arm64
