shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-aba-1_3
image_base_count=1
image_base_1_build_arg=SHIMMY_ABA_BASE_IMAGE
image_base_1_upstream_ref=docker.io/library/fedora:44
image_base_1_default_ref=docker.io/library/fedora@sha256:43b29f65a41eb9c35e1cd5323e3bdf3b655c2357a9f4f1ff2f9c2798e5045d80
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
