shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-aba-1_3
image_base_count=1
image_base_1_build_arg=SHIMMY_ABA_BASE_IMAGE
image_base_1_upstream_ref=registry.access.redhat.com/ubi9/ubi:latest
image_base_1_default_ref=registry.access.redhat.com/ubi9/ubi@sha256:a4b9ec09b1e790a53ef25b7777c539976abe519248264298e5194dcbceac8c31
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
