shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/vszl/ripgrep:latest
image_default_ref=docker.io/vszl/ripgrep@sha256:3e12f460f714b3c4ab27f4dbad8b7eda7b8184050c46c15f95eb0f2f53b5818c
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
