shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/vszl/ripgrep:latest
image_default_ref=docker.io/vszl/ripgrep@sha256:d79cf5d983b28fa346f2fe33b2e07427f62fa34f3848e26118c5f6854d5ad0a8
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
