shimmy_image_config_version=1
image_source=external
image_upstream_ref=ghcr.io/ansible/community-ansible-dev-tools:v26.7.2
image_default_ref=ghcr.io/ansible/community-ansible-dev-tools@sha256:c3b5c90efdd79dd064b9c997fe7bd6e1ee3c6894ecc8270d05257532936af209
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
