ARG SHIMMY_LOGMINE_BASE_IMAGE
FROM ${SHIMMY_LOGMINE_BASE_IMAGE}

ARG SHIMMY_LOGMINE_VERSION=e32a7f656d21fe87b1e1209db4312b728f2f521a

RUN --mount=type=secret,id=shimmy-host-ca-bundle \
  if [ -s /run/secrets/shimmy-host-ca-bundle ]; then \
    cp /run/secrets/shimmy-host-ca-bundle /usr/local/share/ca-certificates/shimmy-host-ca-bundle.crt; \
    update-ca-certificates; \
    rm /usr/local/share/ca-certificates/shimmy-host-ca-bundle.crt; \
  fi

RUN git clone https://github.com/kpfaulkner/gologmine /src/gologmine \
    && cd /src/gologmine \
    && git checkout "${SHIMMY_LOGMINE_VERSION}" \
    && go get github.com/sirupsen/logrus@v1.6.0 \
    && go build -o /usr/local/bin/logmine . \
    && chmod +x /usr/local/bin/logmine

WORKDIR /work

ENTRYPOINT ["logmine"]
