ARG SHIMMY_LOGMINE_BASE_IMAGE=golang:1.22
FROM ${SHIMMY_LOGMINE_BASE_IMAGE}

ARG SHIMMY_LOGMINE_VERSION=v0.1

RUN git clone https://github.com/kpfaulkner/gologmine /src/gologmine \
    && cd /src/gologmine \
    && git checkout "${SHIMMY_LOGMINE_VERSION}" \
    && go build -o /usr/local/bin/logmine ./... \
    && chmod +x /usr/local/bin/logmine

WORKDIR /work

ENTRYPOINT ["logmine"]
