shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-textual-8_2
image_base_count=1
image_base_1_build_arg=SHIMMY_TEXTUAL_BASE_IMAGE
image_base_1_upstream_ref=docker.io/library/python:3.13-slim-bookworm
image_base_1_default_ref=docker.io/library/python@sha256:67a1e1f215ccda113cfc024e8639049257e88f273898f595b61476d128d387e8
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
