shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-textual-8_2
image_base_count=1
image_base_1_build_arg=SHIMMY_TEXTUAL_BASE_IMAGE
image_base_1_upstream_ref=docker.io/library/python:3.13-slim-bookworm
image_base_1_default_ref=docker.io/library/python@sha256:c45a22ea000adfd9cda29364bbe7edd23001ce5cc2ad15857cfbf7766943b9ca
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
