shimmy_image_config_version=1
image_source=external
image_upstream_ref=gcr.io/google.com/cloudsdktool/google-cloud-cli:573.0.0-stable
image_default_ref=gcr.io/google.com/cloudsdktool/google-cloud-cli@sha256:f5fae73a6f1c60b58a1150ff76771a43620891d4dd74abc527c8eca0d544b385
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
