shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/instrumentisto/nmap:7.98-r2
image_default_ref=docker.io/instrumentisto/nmap@sha256:96f6ed194519b62421a1a1c57809e65a7f94d2aa1c8c25676f247e5e148c0827
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
