shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/bats/bats:1.14.0
image_default_ref=docker.io/bats/bats@sha256:5322b877351fda0cc435de8c6116de7d0a2ec79d7c680132a0ef329a633bc66f
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
