shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-logmine-0_1
image_base_count=1
image_base_1_build_arg=SHIMMY_LOGMINE_BASE_IMAGE
image_base_1_upstream_ref=docker.io/library/golang:1.22
image_base_1_default_ref=docker.io/library/golang@sha256:1cf6c45ba39db9fd6db16922041d074a63c935556a05c5ccb62d181034df7f02
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
