shimmy_image_config_version=1
image_source=external
image_upstream_ref=quay.io/skopeo/stable:latest
image_default_ref=quay.io/skopeo/stable@sha256:17da3ac5cadf2b27a3dcf7dea857c4cea558ef757641725fc0eec560030057b3
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
