shimmy_image_config_version=1
image_source=external
image_upstream_ref=quay.io/skopeo/stable:latest
image_default_ref=quay.io/skopeo/stable@sha256:be235f63f7bb2d41b07d1b56bd0ea62b3a8c4d3f43f5f176d4ec832ef02d95a1
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
