shimmy_image_config_version=1
image_source=external
image_upstream_ref=quay.io/skopeo/stable:latest
image_default_ref=quay.io/skopeo/stable@sha256:c7d3c512612f52805023cd38351081dad7e2729fc13d14b701e47c7c8bdd6615
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
