shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/hashicorp/terraform:1.15.6
image_default_ref=docker.io/hashicorp/terraform@sha256:adae45661e45d3c88beef071ee1277b4621cea73517aae7f0844657c8e85f641
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
