shimmy_image_config_version=1
image_source=external
image_upstream_ref=docker.io/linuxserver/keepassxc:latest
image_default_ref=docker.io/linuxserver/keepassxc@sha256:15e9b84880352c7ca30ed8ef6a71d45e0f9417b9dec85d0a7ad1275ce659a3d6
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
