shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-netcat-7_92
image_base_count=1
image_base_1_build_arg=SHIMMY_NETCAT_BASE_IMAGE
image_base_1_upstream_ref=registry.access.redhat.com/ubi9/ubi-minimal:latest
image_base_1_default_ref=registry.access.redhat.com/ubi9/ubi-minimal@sha256:580752f96d36c4132bffd30f9c34865bf4bd87f6aa161c969d117f21732e50f7
image_base_1_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
