shimmy_image_config_version=1
image_source=local-build
image_context=container
image_local_repo=localhost/shimmy-oc-4_18
image_base_count=1
image_base_1_build_arg=SHIMMY_OC_4_18_BASE_IMAGE
image_base_1_upstream_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:16c25aadbd5f564a7c5f1508470f734d676a411b89bd98b307001619d1a5338f
image_base_1_default_ref=registry.redhat.io/openshift4/ose-cli-rhel9@sha256:16c25aadbd5f564a7c5f1508470f734d676a411b89bd98b307001619d1a5338f
image_base_1_registry_access=authenticated
image_platform=linux/amd64
image_platform=linux/arm64
