shimmy_image_config_version=1
image_source=external
image_upstream_ref=public.ecr.aws/aws-cli/aws-cli:2.31.21
image_default_ref=public.ecr.aws/aws-cli/aws-cli@sha256:40033dc921634b1073094712ea8237869bc857cd7ddc2571896ec9b14ef97ae8
image_registry_access=public
image_platform=linux/amd64
image_platform=linux/arm64
